def alr():
    f=open("C:\\Users\\PAYAL-PIU\\AppData\\Local\\Programs\\Python\\Python39\\pyql\\details_.txt","r")
    a=f.readline()
    b=f.readline()
    gh=f.readline()
    f.close()
    import mysql.connector as c
    con=c.connect(host=a,user=b,password=gh)
    cur=con.cursor()
    try:
        b=input("enter database for acessing the table ")
        bc="use {}".format(b)
        cur.execute(bc)
        print(" ")
        cur.execute("show tables;")
        qr=cur.fetchall()
        print(" ")
        for kl in qr:
            print(kl)
        print(" ")
        g=input("enter table name you want to alter ")
        print(" ")
        print("table structure")
        bdc = "desc {}".format(g)
        cur.execute(bdc)
        l=cur.fetchall()
        print(" ")
        for i in l:
            print(i)
        print(" ")
        ge="select * from {}".format(g)
        cur.execute(ge)
        l1=cur.fetchall()
        print("table values")
        print(" ")
        for j in l1:
            print(j)
        print(" ")
        r=input("how do you want to modify it (add, drop) ")
        if r=="add":
            print("preferably use '_' for naming the column for smooth functioning")
            print()
            y=input("enter column_name and its condition ")
        elif r=="drop":
            y=input("enter column_name ")
        ger= "alter table {} {} column {};".format(g,r,y)
        cur.execute(ger)
        print("new table structure")
        bdc = "desc {}".format(g)
        cur.execute(bdc)
        l2=cur.fetchall()
        print(" ")
        for ii in l2:
            print(ii)
        print(" ")
        ge="select * from {}".format(g)
        cur.execute(ge)
        l3=cur.fetchall()
        print("modified table values")
        print(" ")
        for jj in l3:
            print(jj)
        print(" ")
    except c.Error as asr:
        print("something went wrong: {}".format(asr))
