def bld():
    f=open("C:\\Users\\PAYAL-PIU\\AppData\\Local\\Programs\\Python\\Python39\\pyql\\details_.txt","r")
    a=f.readline()
    b=f.readline()
    gh=f.readline()
    f.close()
    import mysql.connector as c
    con=c.connect(host=a,user=b,password=gh)
    cur=con.cursor()
    try:
        cur.execute("show databases;")
        l=cur.fetchall()
        for i in l:
            print(i)
        print(" ")
        b=input("enter database for acessing the table ")
        bc="use {}".format(b)
        cur.execute(bc)
        print(" ")
        cur.execute("show tables;")
        print(" ")
        print("displaying existing tables")
        print(" ")
        qr=cur.fetchall()
        print(" ")
        for kl in qr:
            print(kl)
        print(" ")
        d=input("eneter table name ")
        print(" ")
        print("description of ",d)
        bd = "desc {}".format(d)
        cur.execute(bd)
        lm=cur.fetchall()
        print(" ")
        for ia in lm:
            print(ia)
        print(" ")
        print( "functions for blend: ")
        print("sum ---- to get the cum of all the values")
        print("avg ---- to get the average of all the values")
        print("count -- to get the count of all records")
        print("min ---- to get the minimum of all the values")
        print("max ---- to get the maximum value")
        print("std ---- to get population standard deviation")
        print(" ")
        print(" ")
        print("if you want to include all columns then enter '*' in the below input")
        print(" ")
        f=input("enter statement to aggregate records in format(function_(column_name)")
        df= "select {} from {};".format(f,d)
        cur.execute(df)
        ty=cur.fetchall()
        print("  ")
        for twe in ty:
            print(twe)
        print("  ")
    except c.Error as asj:
        print("something went wrong: {}".format(asj))
