def cot():
    f=open("C:\\Users\\PAYAL-PIU\\AppData\\Local\\Programs\\Python\\Python39\\pyql\\details_.txt","r")
    a=f.readline()
    b=f.readline()
    gh=f.readline()
    f.close()
    import mysql.connector as c
    con=c.connect(host=a,user=b,password=gh)
    cur=con.cursor()
    try:
        cur.execute("show databases;")
        l=cur.fetchall()
        for i in l:
            print(i)
        print(" ")
        b=input("enter database for acessing the table ")
        bc="use {}".format(b)
        cur.execute(bc)
        print(" ")
        cur.execute("show tables;")
        print(" ")
        print("displaying existing tables")
        print(" ")
        qr=cur.fetchall()
        print(" ")
        for kl in qr:
            print(kl)
        print(" ")
        gk = input("enter table name ")
        print("displaying description of table ")
        print(" ")
        hu = "desc {}".format(gk)
        cur.execute(hu)
        ku = cur.fetchall()
        print(" ")
        for gh in ku:
            print(gh)
        print(" ")
        cj = input("enter arguments to concat,like - column_name,'_seperator_',column_name ")
        cy = input("enter column to be displayed individually ")
        dx = "select concat( {} ) as 'mnc', {} from {} ".format(cj,cy,gk)
        cur.execute(dx)
        sa = cur.fetchall()
        print(" ")
        for bvr in sa:
            print(bvr)
        print(" ")
    except c.Error as asb:
        print("something went wrong: {}".format(asb))
