def dlet():
    f=open("C:\\Users\\PAYAL-PIU\\AppData\\Local\\Programs\\Python\\Python39\\pyql\\details_.txt","r")
    a=f.readline()
    b=f.readline()
    gh=f.readline()
    f.close()
    import mysql.connector as c
    con=c.connect(host=a,user=b,password=gh)
    cur=con.cursor()
    cur.execute("show databases;")
    l=cur.fetchall()
    for i in l:
        print(i)
    print(" ")
    print(" ")
    try:
        b=input("enter database for acessing the table ")
        bc="use {}".format(b)
        cur.execute(bc)
        print(" ")
        cur.execute("show tables;")
        qr=cur.fetchall()
        print(" ")
        for kl in qr:
            print(kl)
        print(" ")
        d=input("enter table name ")
        bdc = "desc {}".format(d)
        cur.execute(bdc)
        l=cur.fetchall()
        print("description of ",d)
        print(" ")
        for i in l:
            print(i)
        print(" ")
        print("displaying existing values")
        bdc = "select * from {}".format(d)
        cur.execute(bdc)
        li=cur.fetchall()
        print(" ")
        for ik in li:
            print(ik)
        print(" ")
        r=input("enter condition - where ")
        dr="delete from {} where {};".format(d,r)
        cur.execute(dr)
        con.commit()
        print("record deleted")
    except c.Error as asp:
        print("something went wrong: {}".format(asp))
