def enu():
    print(" ")
    print("commands in table")
    print(" ")
    print("alter ---------- to alter a table")
    print("back ----------- to end end the working with tables")
    print("blend ---------- to use aggregate functions")
    print("concat --------- to display values using concat function")
    print("create --------- to create a table")
    print("delete --------- to delete values from a table ")
    print("desc ----------- to know the description of the table")
    print("display -------- to display particular columns with conditions")
    print("having --------- to use having clause")
    print("index ---------- to see the index")
    print("insert --------- to insert values into a table")
    print("join ----------- to join two tables")
    print("order ---------- to order by the columns")
    print("remove table --- to delete a table")
    print("see tables ----- to see tables")
    print("see values ----- to see values from a table")
    print("table syntax --- to see synatx of the table")
    print("update --------- to update a table")
    print(" ")
