def odr():
    f=open("C:\\Users\\PAYAL-PIU\\AppData\\Local\\Programs\\Python\\Python39\\pyql\\details_.txt","r")
    a=f.readline()
    b=f.readline()
    gh=f.readline()
    f.close()
    import mysql.connector as c
    con=c.connect(host=a,user=b,password=gh)
    cur=con.cursor()
    cur.execute("show databases;")
    l=cur.fetchall()
    for i in l:
        print(i)
    print(" ")
    try:
        b=input("enter database for acessing the table ")
        bc="use {}".format(b)
        cur.execute(bc)
        print(" ")
        cur.execute("show tables;")
        print(" ")
        print("displaying existing tables")
        print(" ")
        qr=cur.fetchall()
        print(" ")
        for kl in qr:
            print(kl)
        print(" ")
        dg = input("enter table name")
        print(" ")
        sr = "desc {}".format(dg)
        cur.execute(sr)
        ny = cur.fetchall()
        print(" ")
        print("decription of ",dg)
        print(" ")
        for qx in ny:
            print(qx)
        print(" ")
        ti = "select * from {}".format(dg)
        cur.execute(ti)
        sf = cur.fetchall()
        print(" ")
        print("displaying existing values")
        print(" ")
        for ll in sf:
            print(ll)
        print(" ")
        kj = input("order by which column ")
        fd = "select * from {} order by {}".format(dg,kj)
        print(fd)
        cur.execute(fd)
        cg = cur.fetchall()
        print(" ")
        for hj in cg:
            print(hj)
        print(" ")
    except c.Error as asc:
        print("something went wrong: {}".format(asc))
